### ISSUE TITLE
iMessage not working even after SMBIOS change

### ISSUE THREAD

**Issue by PikaGamer8** [notAperson535/OneClick-macOS-Simple-KVM#102]
**Which operating system are you trying to install?**
I am on macOS Ventura.

**Describe the bug**
Whenever signing in, I get one of two errors, I get into the Messages app but after 10 seconds I get kicked out or get the error that an unknown error has occured. 

**To Reproduce**
1. Go to 'Messages'
2. 'Sign in'
3. 'Wait around 10 seconds after sign in'
4. Messages kicks me out

**Expected behavior**
To be able to use iMessage and FaceTime

**Screenshots / Recordings**

https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/77557847/78d60ca6-f41d-46f0-b3b5-85dc9852318b

[config.plist in the ZIP file](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/files/14323659/config.zip)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS on Windows 10/11 x86_64 (WSL2)
 - Version 22.04.4 LTS

**Additional context**
Apple Store and iCloud do work.
I have also tried everything in the OpenCore guide and OneClick guide (https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html and https://oneclick-macos-simple-kvm.notaperson535.is-a.dev/docs/guide-Apple-ID) including fixing en0, ROM, etc. I have even tried different SMBIOS and my Apple ID is confirmed to not be in spam.

**Comment by PikaGamer8** [comment]
Partially solved: Only works on Catalina

**Comment by notAperson535** [comment]
Try doing this: https://support.apple.com/en-us/HT201251

**Comment by PikaGamer8** [comment]
> Try doing this: https://support.apple.com/en-us/HT201251

Thanks for the advice, but I have it working now and am back in Ventura after upgrading from Catalina. Thanks for the help and this project! 😊

**Comment by PikaGamer8** [comment]
To anyone else in this scenario, you could either try what notAperson535 suggested above or you could go with my method of restarting in Catalina, getting a customer code, and talk to Apple Support. I tried notAperson535's method on a new Apple ID on a spare computer and it worked so their idea is definitely the easiest.
