### ISSUE TITLE
USB (including Keyboard and Mouse) Don't Work on macOS 14.4 Sonoma

### ISSUE THREAD

**Issue by manuth** [notAperson535/OneClick-macOS-Simple-KVM#103]
**Which operating system are you trying to install?**
macOS Sonoma

**Describe the bug**
When running macOS using the `make.sh --add`, USB devices including keyboard and mouse don't work.

**To Reproduce**
1. Install macOS Minterey using the "Manual Installation" guide
2. Add the VM to virt-manager using `make.sh --add`
3. Take note that mouse and keyboard still work
4. Upgrade your macOS in the settings app
5. Take note that after a reboot, both mouse and keyboard don't work anymore.

**Expected behavior**
Mouse and keyboard input should be picked up

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Version: latest

**Additional context**
The issue has been described in a reddit post found here:
<https://www.reddit.com/r/macOSVMs/s/kzSuQrgOgt>

As it looks, it's due to macOS dropping support for USB 2.

Switching to `qemu-xhci` is adviced. 

I believe I managed it to fix it by doing exactly that, but I need to test it first.

Probably related to #87

**Comment by notAperson535** [comment]
This is a well known issue at this point, make sure to tell me how you edited the virt manager so I can update the repo

**Comment by manuth** [comment]
No worries, will do 😄

**Comment by emoffett** [comment]
I have created a pull request that has solved this issue for me: https://github.com/notAperson535/OneClick-macOS-Simple-KVM/pull/104

Please let me know if you need more in order to accept it.

**Comment by manuth** [comment]
Alright!
I created a PR #105 addressing the `libvirt`-part.

**Comment by ErichPetersen** [comment]
I am unable to access the iPhone via the USB port on MacOS Moterey.
Is anyone else experiencing the same problem?
These are the parameters I'm using for the USB port:

-usb -device qemu-xhci,id=ehci -device usb-kbd -device usb-tablet \
-usb -device usb-host,bus=ehci.0,vendorid=0x05ac,productid=0x12a8,guest-reset=false,id=iphone \
