### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mariorengifo1986** [notAperson535/OneClick-macOS-Simple-KVM#108]
**Which operating system are you trying to install?**
Ventura

**Describe the bug**
The vm can´t conect to the internet i already config the brigde but withtout luck

**To Reproduce**
clone the repo
start the vm 
click installer 
tha vm cant conect to internet 

**Expected behavior**

just install

**Screenshots**
 the recovery cant connect the servers

**Desktop (please complete the following information):**
arch linux
ryzen procesor 
 - rolling release 

**Additional context**
this worked 

https://christitus.com/macos-on-linux/

**Comment by notAperson535** [comment]
So you’re saying the bridged network guide from that website worked?

**Comment by mariorengifo1986** [comment]
Exactly!!! i already spend 12+ hours trying to fix the network but i couldn't. Thanks for the promptly response!!! i ijust gave up ... i'll continue with arch linux.

**Comment by notAperson535** [comment]
@mariorengifo1986 So would it be beneficial if I made some mention of it or added it to the docs?

**Comment by mariorengifo1986** [comment]
Hi after more time invested to this i cant make it. i can't make to work. i search other proyects (sorry) https://github.com/Coopydood/ultimate-macOS-KVM and this eventualy let me install the os. However i can't install sonoma. The Network config gave me a bad time but the python script of that proyect let me install monterey. This repository as well as https://github.com/kholia/OSX-KVM wasn't able to connect to the server. I still don´t know why. Thanks for your work!!!

**Comment by notAperson535** [comment]
@mariorengifo1986 try replacing the line in basic.swh with `vmxnet3` with
```
-device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
```

**Comment by mariorengifo1986** [comment]
No luck...

**Comment by mariorengifo1986** [comment]
Sorry. No luck maybe is the MAC address.

**Comment by mariorengifo1986** [comment]
Hi me again!. finally it worked. The problem was de phsyical address and the router i'm on arch linux 

i came up with this part of the wiki 
Troubleshooting
Swapping computers on the cable modem

Some cable ISPs (Vidéotron for example) have the cable modem configured to recognize only one client PC, by the MAC address of its network interface. Once the cable modem has learned the MAC address of the first PC or equipment that talks to it, it will not respond to another MAC address in any way. Thus if you swap one PC for another (or for a router), the new PC (or router) will not work with the cable modem, because the new PC (or router) has a MAC address different from the old one. To reset the cable modem so that it will recognise the new PC, you must power the cable modem off and on again. Once the cable modem has rebooted and gone fully online again (indicator lights settled down), reboot the newly connected PC so that it makes a DHCP request, or manually make it request a new DHCP lease.

If this method does not work, you will need to clone the MAC address of the original machine. See also [MAC address spoofing](https://wiki.archlinux.org/title/MAC_address_spoofing).


So after i did that the script worked flawlessly. even though this script https://github.com/Coopydood/ultimate-macOS-KVM  achieve to install the OS i couldn't boot into it after installation. So Thank you for your work. I think this problem could happen to someone else.  
![imagen](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/13718853/b240a765-d29c-4796-9f22-af27cd464816)
![imagen](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/13718853/ab448067-97ae-4d07-85c6-8b9012f60d8b)
