### ISSUE TITLE
Is it possible to use an attachable mode? 

### ISSUE THREAD

**Issue by chopin1998** [notAperson535/OneClick-macOS-Simple-KVM#109]
Can we use a detachable mode?
That way, we can close the GUI anytime and switch to headless mode, and then reattach it when needed without disrupting the background process.

Thank you!

**Comment by notAperson535** [comment]
If it’s possible in qemu you can just add it to the args in basic.sh

**Comment by notAperson535** [comment]
@chopin1998 found it. Put `-daemonize` in the args for basic.sh
