### ISSUE TITLE
No installer option in OpenCore boot menu

### ISSUE THREAD

**Issue by igorkulman** [notAperson535/OneClick-macOS-Simple-KVM#111]
**Which operating system are you trying to install?**
Monterey / Ventura / Sonoma

**Describe the bug**
No matter which macOS version I try to install there is never the installer boot option in OpenCore

**To Reproduce**
1. runs setup.sh
2. Wait for qemu to open
3. observe there is no installer to boot from

**Expected behavior**
installer showing up in the boot menu

**Screenshots**
![Screenshot from 2024-07-23 14-01-13](https://github.com/user-attachments/assets/29ef0fc5-bf78-4edf-87a5-2a01e14f5881)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Version  22.04 LTS

**Comment by notAperson535** [comment]
@igorkulman that is the installer. Just hit enter to launch it
