### ISSUE TITLE
Bug Report: Boot crashes, then reboots system.

### ISSUE THREAD

**Issue by BrattishRat384** [notAperson535/OneClick-macOS-Simple-KVM#118]
**MacOS Sonoma**

>Ran the MacOS Installer overnight, and found the system rebooted to the disk selection menu, the installer has now been replaced with an Recovery Menu, and an option for MacOS has appeared (where the OS was installed), the recovery does show the disk as having MacOS installed, but unable to boot the disk.
When the disk is selected a menu shows 'Your computer restarted because of a problem. Press any Key or wait a few seconds to continue starting up.'
The terminal only shows that failed to initialize DAC, and shows an error about pulseAudio.
First Aid also shows no issues with the disk.
The drive does show as bootable in the MacOS Recovery.

**Steps to reproduce the behavior:**
1. Follow the one click installer guild, and select Sonoma.
2. Once installed select the boot drive (In my case I named it MacOS)
3. Wait for it to boot, and it should show the error menu.
4. Terminal doesn't show any errors.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Version: Latest as of Aug 31

**Additional context**
>Just in testing while writing this, I rebooted the VM and it has now completly locked up after selecting the boot drive. Should I reinstall the system again? 
>I did read somewhere that for mackintosh that there could be compatibility issues with my system (Gigabyte G5GD) But I've had no issues with Sosumi, I just wanted to update to the latest version of MacOS.

---
**Screenshots**
![Screenshot from 2024-08-31 10-22-11](https://github.com/user-attachments/assets/1b6a677d-def5-48a4-9134-699c706910ba)
![image](https://github.com/user-attachments/assets/69b12e2d-549b-4529-ae42-39fddd90f74e)
![image](https://github.com/user-attachments/assets/4c6ee82f-e069-402e-b15b-db840785f558)

**Comment by notAperson535** [comment]
@BrattishRat384 have you changed any core counts in the basic.sh file? Some configurations don’t work

**Comment by BrattishRat384** [comment]
> @BrattishRat384 have you changed any core counts in the basic.sh file? Some configurations don’t work

Hello,
Yes, I have changed it to 4 cores and 16gb ram. Should I change it to something else?

**Comment by notAperson535** [comment]
@BrattishRat384 revert all your changes to basic.sh and try again. If it seems to be the issue, you can try playing around with different core configurations.

**Comment by BrattishRat384** [comment]
@notAperson535
I just tried, and I think the disk may be .qcow2 might be corrupted as no matter what I select I get that error menu, and a reboot.
Should I try a fresh install?

**Comment by notAperson535** [comment]
@BrattishRat384 Yes, and if you didn’t already, select macOS extended journaled while formatting the disk

**Comment by BrattishRat384** [comment]
@notAperson535
Just followed the manual installation steps, just running the recovery installer, I used extended journal last time, I'll let you know how it goes. It's got about 4 hours left.

**Comment by BrattishRat384** [comment]
@notAperson535 
Ive just finished the installer (again) and now when I select any option I get this menu
![image](https://github.com/user-attachments/assets/da13f73f-24cb-46e8-971f-37c1f99764bd)

**Comment by notAperson535** [comment]
@BrattishRat384 Your disk has enough space for this install right?

**Comment by BrattishRat384** [comment]
@notAperson535 it's a fresh install of PopOS on an external 1tb HDD, I think it's only taking like 20gb for the install, and I've allocated 125gb for it, should have plenty of storage left.
Next option would be to test it on windows I guess?

**Comment by notAperson535** [comment]
@BrattishRat384 make sure that kvm is enabled properly on your machine.

**Comment by BrattishRat384** [comment]
@notAperson535 
Virtualization is enabled on my laptop, I'm going to test an install on windows instead, and Ill try port the current install to my server to make sure its not a problem with my laptop, as I've had no issues on the server.

**Comment by BrattishRat384** [comment]
Just tried another project just to check if it's my system, I have Sosumi working in Bug-Sur, but I haven't been able to get Sonma to work at all, so I might trail a different version instead.
Thanks so much for the support @notAperson535.
