### ISSUE TITLE
Keyboard layout is broken (Windows VNC)

### ISSUE THREAD

**Issue by RealAlphabet** [notAperson535/OneClick-macOS-Simple-KVM#12]
Thank you for your awesome work !

It works fine, but unfortunately the keyboard layout is definitely broken and I couldn't find any solution on the web for it.

Maybe related to VNC, I'm using an AZERTY (FR) keyboard and I can't type numbers or special characters on Mac.
I used your project to use XCode on Windows, not having the possibility to use `[`,`]`,`{`,`}`,`(`,`)`,`,` and `.` is a bit annoying.

Probably not related to your project but if you have an idea where it came from, it would be really nice to share it on the tutorial.

**Comment by notAperson535** [comment]
@RealAlphabet Maybe you could change the keyboard layout in macOS?

**Comment by notAperson535** [comment]
@RealAlphabet change this section `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd`
to the correct keyboard layout [found here](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/AppleKeyboardLayouts/AppleKeyboardLayouts.txt)

**Comment by notAperson535** [comment]
@RealAlphabet I'm assuming my solution worked so I closed the issue. Please tell me if it was not fixed and I will reopen this.

**Comment by RealAlphabet** [comment]
> @RealAlphabet I'm assuming my solution worked so I closed the issue. Please tell me if it was not fixed and I will reopen this.

Sorry for the delay in response. I couldn't try under Windows because the VM was lagging too much and I had uninstalled it. I tried it when I was on Linux and your solution worked. Thank you very much for your time.

**Comment by RealAlphabet** [comment]
Up: It doesn't seem to work on Windows on an Azerty FR keyboard.

**Comment by notAperson535** [comment]
@RealAlphabet Great to see you fixed it!
