### ISSUE TITLE
2GB disk only not 64GB per documentation

### ISSUE THREAD

**Issue by joelrb** [notAperson535/OneClick-macOS-Simple-KVM#120]
**Which operating system are you trying to install?**
macOS Sonoma

**Describe the bug**
I followed all the instructions on Installing on Windows. No error encountered.

But when all is done, there's on 2.87GB disk total. 

How to increase?

**Expected behavior**
64GB disk per documentation

**Screenshots**
![Screenshot 2024-09-02 195803](https://github.com/user-attachments/assets/14e85c0a-c94a-4a42-b178-9465763f8f0d)

**Desktop (please complete the following information):**
 - OS: Ubuntu in WSL
 - Version 24.04 LTS

**Comment by notAperson535** [comment]
@joelrb Click view, then `show all devices`, and the drive should appear

**Comment by joelrb** [comment]
> @joelrb Click view, then `show all devices`, and the drive should appear

Thanks! Found it.
