### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by Akmal-arch** [notAperson535/OneClick-macOS-Simple-KVM#121]
**Which operating system are you trying to install?**
macOS High Sierra

**Describe the bug**
After downloading macos dmg file it says qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory

My laptop:
i5-13420h
rtx2050
8gb

**Comment by notAperson535** [comment]
@Akmal-arch how much RAM does your machine have and how much are you trying to assign to the VM? There could also be other processes on your machine that are taking up RAM. Also, what host OS are you running? If you’re running windows, you may want to try dual booting Linux as your machine does not have much RAM, and Linux performs better than windows in those situations.

**Comment by Akmal-arch** [comment]
Thank you for help, i solved it
