### ISSUE TITLE
Bug Report - Cannot sign into apple account (account not blocked)

### ISSUE THREAD

**Issue by DeanVanGreunen** [notAperson535/OneClick-macOS-Simple-KVM#124]
**Which operating system are you trying to setup?**
macOS 15 Sequoia

**Describe the bug**
unable to sign into apple developer account.

**To Reproduce**
Try to sign with you apple developer account, with correct username and password

**Expected behavior**
be able to login after verifying account via phonecall, or sms

**Screenshots**
![image](https://github.com/user-attachments/assets/92cc709e-6085-4fd0-bca3-8f2f440ea40f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04LTS via WSL2
 - Version 20.04LTS

**Additional context**
everything else works correctly, just unable to sign into my apple account

**Comment by notAperson535** [comment]
@Wykks And you’ve confirmed and tested this works?

**Comment by notAperson535** [comment]
@Wykks Thanks! I will be updating the config soon.

**Comment by notAperson535** [comment]
#126
