### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory. Now fixed with simple update `git pull --rebase`

### ISSUE THREAD

**Issue by ctvw** [notAperson535/OneClick-macOS-Simple-KVM#13]
When running ./setup.sh, I receive this message:

/usr/bin/env: ‘bash\r’: No such file or directory

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
qemu-system is already the newest version (1:4.2-3ubuntu6.21).
qemu-utils is already the newest version (1:4.2-3ubuntu6.21).
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

/usr/bin/env: ‘python3\r’: No such file or directory

qemu-img: Could not open 'BaseSystem.dmg': Could not open 'BaseSystem.dmg': No such file or directory
/usr/bin/env: ‘bash\r’: No such file or directory
```

I've tried using _dos2unix setup.sh_, and _sed $'s/\r$//' setup.sh_  before ./setup.sh, and still having issues. Any idea?

**Comment by notAperson535** [comment]
@ctthomas Can I see what your setup.sh file looks like?

**Comment by notAperson535** [comment]
Actually, please run this command `./tools/debug.sh`

**Comment by ctthomas** [comment]
@notAperson535 I get the same message: 

$ ./tools/debug.sh
/usr/bin/env: ‘bash\r’: No such file or directory

**Comment by notAperson535** [comment]
@ctthomas what OS are you on? Is it NixOS?

**Comment by s-n-g** [comment]
What does that gives you?

```
which env
```

**Comment by s-n-g** [comment]
> @ctthomas what OS are you on? Is it NixOS? Windows?

It seems the file has **Windows** line endings...
Have you edited the file (or even opened and saved without altering it?)

Possible solution would be to check `~/.gitconfig` and make sure `autocrlf=true` does not exist...

Other than that, maybe this would help

```
dos2unix basic.sh
```

**Comment by notAperson535** [comment]
> > @ctthomas what OS are you on? Is it NixOS? Windows?
> 
> @ctthomas it seems the file has **Windows** line endings... Have you edited the file (or even opened and saved without altering it?)

It shouldn't have windows lines, as I made it in github

> ```
> dos2unix basic.sh
> ```

It's `setup.sh`, and they already tried `dos2unix setup.sh`

**Comment by notAperson535** [comment]
> I've tried using _dos2unix setup.sh_, and _sed $'s/\r$//' setup.sh_ before ./setup.sh, and still having issues. Any idea?

`setup.sh` is not the problem. It's the `fetch-macOS-v2` file on line 1

**Comment by ctthomas** [comment]
@notAperson535 I'm on Windows 11. Running this in a Ubuntu 20.04 WSL2.

**Comment by notAperson535** [comment]
@ctthomas go ahead and run this command `git pull --rebase`, and then try again

**Comment by ctthomas** [comment]
Seems to fix that issue, this returns:

```
Unable to init server: Could not connect: Connection refused
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
alsa: Could not initialize DAC
alsa: Failed to open `default':
alsa: Reason: No such file or directory
audio: Failed to create voice `dac'
gtk initialization failed
```

**Comment by notAperson535** [comment]
> Once setup.sh finsishes , press ctrl+c and run sudo HEADLESS=1 ./basic.sh. Once this is done, download VNC Viewer, [here](https://www.realvnc.com/en/connect/download/viewer/), then type localhost:5900 into the top to connect to the vm using vnc.
Whenever you want to load up the machine again, run sudo HEADLESS=1 ./basic.sh, NOT ./setup.sh.

@ctthomas
