### ISSUE TITLE
No such file or directory when importing to Virt-Manager.

### ISSUE THREAD

**Issue by aia832003** [notAperson535/OneClick-macOS-Simple-KVM#14]
I'm getting the following error when attempting to import into Virt Manager. I'm running Fedora 35 GNOME desktop.

```
./make.sh --add
template.xml has been generated in /home/aia832003/Documents/notAperson535-OneClick-macOS-Simple-KVM-61657ee
[sudo] password for aia832003: 
error: Failed to define domain from template.xml
error: Cannot check QEMU binary /run/current-system/sw/bin/qemu-system-x86_64: No such file or directory
```

**Comment by notAperson535** [comment]
@aia832003 before we try anything else, run `git pull --rebase` in the root directory, and try it again.

**Comment by aia832003** [comment]
@notAperson535 git pull --rebase
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by notAperson535** [comment]
@aia832003 install git, then do a `git clone https://github.com/notAperson535/OneClick-macOS-Simple-KVM.git`, and try again

**Comment by aia832003** [comment]
I've tried that too.

Andrew Allen

**Comment by notAperson535** [comment]
@aia832003 are you using a custom qemu binary?

**Comment by notAperson535** [comment]
@aia832003 actually try creating a symlink to `/usr/libexec/qemu-kvm`

**Comment by notAperson535** [comment]
@aia832003 sorry, I said the wrong directory create a symlink to `/run/current-system/sw/bin/`

**Comment by notAperson535** [comment]
@aia832003 install the regular version of QEMU, it should work fine.

**Comment by aia832003** [comment]
Thanks for your patience. I've used the installation directly from QEMU's site with the same results of missing file or directory when using the ./make.sh --add command.

Andrew Allen

**Comment by notAperson535** [comment]
@aia832003 remove the old qemu repository version and remove the symlink I told you to use. Then try again.

**Comment by AbrarSL** [comment]
I got this error as well. I fixed it by manually editing the template.xml file. I changed the line that referred to `run/current-system/sw/bin/qemu-system-x86_64` with `/usr/bin/qemu-system-x86_64` which is where the binary is actually stored on my system (Arch Linux).

**Comment by notAperson535** [comment]
> I got this error as well. I fixed it by manually editing the template.xml file. I changed the line that referred to `run/current-system/sw/bin/qemu-system-x86_64` with `/usr/bin/qemu-system-x86_64` which is where the binary is actually stored on my system (Arch Linux).

that sounds like it should work

**Comment by notAperson535** [comment]
> > I got this error as well. I fixed it by manually editing the template.xml file. I changed the line that referred to `run/current-system/sw/bin/qemu-system-x86_64` with `/usr/bin/qemu-system-x86_64` which is where the binary is actually stored on my system (Arch Linux).
> 
> that sounds like it should work

@aia832003

**Comment by notAperson535** [comment]
I'm assuming this is closed
