### ISSUE TITLE
Apple ID issue 

### ISSUE THREAD

**Issue by tejas-luthra** [notAperson535/OneClick-macOS-Simple-KVM#15]
Can't sign in using an apple id. When I go to create a new one, It says that this mac has been used to create too many apple ids.

**Comment by tejas-luthra** [comment]
I tried that. It still says that I can't sign it with my apple id but I can create one for some reason.

**Comment by tejas-luthra** [comment]
I signed in one with it and now it signed me out.

**Comment by notAperson535** [comment]
@tejas-luthra do you have too many devices with that apple id?

**Comment by tejas-luthra** [comment]
I only have my iphone with that appleID

**Comment by notAperson535** [comment]
@tejas-luthra try doing the docs guide for it again, and use a different uuid

**Comment by notAperson535** [comment]
This seems like a common problem recently, probably apple did something.

**Comment by jsoques** [comment]
> @tejas-luthra you can use this guide: https://oneclick-macos-simple-kvm.notaperson535.is-a.dev/docs/apple-id/

Page not found. Any fix on this? I had a working VM but did a `git pull --rebase` and it messed up.

**Comment by notAperson535** [comment]
@jsoques the page should be fixed now. Also, check the vm specs because a `git pull --rebase` usually messes them up.

**Comment by jsoques** [comment]
Thanks

**Comment by jhonpedro** [comment]
To make things work over here I had to create a new account at Apple, just then my login with this new account worked

**Comment by brianbert** [comment]
can you make a dumb version of the Apple ID fix doc? I don't get where to paste things, thanks in advance.

**Comment by notAperson535** [comment]
@jhonpedro thank you!!!

**Comment by notAperson535** [comment]
@brianbert made a chart for where the values: https://github.com/notAperson535/OneClick-macOS-Simple-KVM/commit/ee3eef076a374461575e36462db36ec36a80dfdd
