### ISSUE TITLE
QEMU crashes during mac os setup screen

### ISSUE THREAD

**Issue by sdncd** [notAperson535/OneClick-macOS-Simple-KVM#16]
Mac big sur os closes on the setting up mac os screen, this is using the oneclick method fedora 64x

**Comment by notAperson535** [comment]
@sdncd what do you mean by "randomly closes?" please give more details

**Comment by sdncd** [comment]
It

> @sdncd what do you mean by "randomly closes?" please give more details

Qemu closes for no reason during installing mac os screen, formatted the partion as the guide says and my device is supported by mac os

**Comment by notAperson535** [comment]
@sdncd so qemu is crashing?

**Comment by sdncd** [comment]
> @sdncd so qemu is crashing?

Yep

**Comment by notAperson535** [comment]
@notAperson535 try an older os like catalina and see if it crashes

**Comment by sdncd** [comment]
> @notAperson535 try an older os like catalina and see if it crashes

Tried it same issue

**Comment by sdncd** [comment]
Any updates on the issue?

**Comment by notAperson535** [comment]
@sdncd I think it is a QEMU issue, try using virt-manager instead

**Comment by sdncd** [comment]
May i ask how do i import? ./make.sh --add doesn't work for me

**Comment by notAperson535** [comment]
@sdncd it should work, just make sure the libvirtd service is running. Sorry for the late response.
