### ISSUE TITLE
qxl_send_events: spice-server bug: guest stopped, ignoring

### ISSUE THREAD

**Issue by sesu-64** [notAperson535/OneClick-macOS-Simple-KVM#17]
**Describe the bug**
QEMU does not launch at all when trying to run ./basic.sh 

**To Reproduce**
Follow the instructions in the manual install or use the one click option and reach the point at which ./basic.sh is ran

**Expected behavior**
QEMU runs and the vm boots

**Desktop:**
 - OS: Arch Linux

**Additional context**
Using the awesome window manager and no desktop environment

**Comment by notAperson535** [comment]
@sesu-64 you can use the headless version and ssh into it as you have no gui? Would that be an option?

**Comment by sesu-64** [comment]
why would I want to do that? and what do you mean "as you have no gui"?

**Comment by notAperson535** [comment]
@sesu-64 A GUI is a graphical user interface aka a desktop environment. correct me if I am wrong, but I am understanding that you have no desktop environment, but have a window manager. I would use [VNC Viewer](https://www.realvnc.com/connect/download/viewer/) and connect to port `localhost:5900` after starting the machine with this command: `sudo HEADLESS=1 ./basic.sh`

**Comment by sesu-64** [comment]
Ok, I think something might be getting lost in the translation here, because a window manager IS as much of a graphical user interface as a full desktop environment, except it comes with no other gui programs like file managers or settings. That aside, I didn't manage to solve the spice-server bug, but running the basic.sh script and then running vncviewer :5900 gets me the window to show up in spite of the bug report, and running with virtio.sh achieves the same without throwing any errors, so I guess that's gonna be how I run the thing now, anyways, I suppose bigger desktop environments have vncviewer set to always listen and pop up a window if a qemu-system runs but I just had to run that command up there and it works, anyways, thank you for maintaining this project and sorry if my issue was a bit annoying to listen to.

**Comment by notAperson535** [comment]
@sesu-64 Glad you figured it out! I will close this issue now. And no, you were not annoying to listen to.
