### ISSUE TITLE
Unable to run Monterey

### ISSUE THREAD

**Issue by hockeymikey** [notAperson535/OneClick-macOS-Simple-KVM#18]
**Describe the bug**
I am unable to install or upgrade to Monterey on my system. It always hangs at the beginning of selecting the installation medium (this is trying a fresh install, or even an upgrade from inside BigSur)

I think this is an accurate description of what I am experiencing: 
https://www.reddit.com/r/hackintosh/comments/ud7b6r/stuck_on_boot_for_monterey_on_optiplex_7050/

I get this when using a default install from the repo. When I try using a fixed EFI in this thread:

https://forum.amd-osx.com/index.php?threads/amd-rayon-r7-5800h-install-monterey-kernel-panic.2725/page-12#posts

I get this issue instead (which I assume is further along).
https://www.reddit.com/r/hackintosh/comments/u8ukbx/opencore_080_monterey_installation_stalling/
https://www.tonymacx86.com/threads/big-sur-installer-error-in-opening-usr-standalone-os-dmg-root_hash.306845/

Some other links I had up in researching this issue:
https://github.com/acidanthera/CpuTscSync
https://www.reddit.com/r/hackintosh/comments/us9wog/update_legion_5_with_rx6600m_gpu_acceleration/

I feel it may be because of lack of tsc_adjust support but I have not tried single CPU yet. I could test more but need to learn how to build OpenCore. There is a repo I found with a make file but requires MacOS so gotta figure that one out first. 

**Desktop**
 - OS:ArchLinux
 -  Omen 15 2020 (Ryzen 4800H)

**Comment by notAperson535** [comment]
@hockeymikey you can run this command `git pull origin preview` and then modify the efi folder inside of the opencore folder. once you are done run this command to rebuild opencore. `rm -f OpenCore.qcow2; sudo ./opencore-image-ng.sh --cfg config.plist --img OpenCore.qcow2`

**Comment by notAperson535** [comment]
@hockeymikey try the new opencore image with `git pull --rebase`. It has a tsc adjust.
