### ISSUE TITLE
Could not open 'BaseSystem.img': No such file or directory

### ISSUE THREAD

**Issue by swaggyP36000** [notAperson535/OneClick-macOS-Simple-KVM#2]
> qemu-system-x86_64: -drive id=InstallMedia,format=raw,if=none,file=BaseSystem.img: Could not open 'BaseSystem.img': No such file or directory

Running setup.sh doesn't seem to download BaseSystem.dmg. The script throws that error after the fact

**Comment by swaggyP36000** [comment]
**Update**

I made my own fork to test out some changes, and here's what works:

1. Added fetch-macOS-v2.py from https://github.com/kholia/OSX-KVM and altered setup.sh to use that instead of your .py script. For some reason, yours doesn't properly download BaseSystem.dmg. This does limit the options, but as an end user that wants to get a virtual machine on Monterey, this is a viable solution to me
2. "chmod u+rwx fetch-macOS-v2.py" before running the new .py script - for me personally, without that it throws an access denied error, so just in case. No harm in keeping it there anyway
3. Added the line "qemu-img convert BaseSystem.dmg -O raw BaseSystem.img" under ./fetch-macOS-v2.py. Somehow your update omits the .dmg -> .img conversion

Your fetch-macOS.py script also has a typo on the last line.

I'm not too keen on how GitHub works, but you're free to borrow changes if you want, although most of the lines I added are either intuitive or can be found from kholia's github anyway

**Comment by notAperson535** [comment]
@swaggyP36000 I was testing a different script, but originally I used the exact same script, I have just reverted to it. Thank you for the feedback.

**Comment by notAperson535** [comment]
@swaggyP36000 I have fixed this repository so it should work fine for you now.

**Comment by swaggyP36000** [comment]
@notAperson535 Much appreciated - right now I have my own fork that installs Monterey. If there are any more updates (like newer opterating systems being added, I'll be sure to check back

**Comment by notAperson535** [comment]
@swaggyP36000 you can come back to this fork and transfer the macOS.qcow2 and BaseSystem.img files if you want. Can you close this issue?
