### ISSUE TITLE
Idea: Community Discord

### ISSUE THREAD

**Issue by strich3** [notAperson535/OneClick-macOS-Simple-KVM#20]
**Is your feature request related to a problem? Please describe.**

> A Community Discord where you have the basic Channels like community-support, general and an GitHub Update Channel

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/179815630-e37b9c4c-da59-4a00-a120-f224ccf6bb1f.png)
can't join via the discord link., what could be the issue.?

**Comment by notAperson535** [comment]
@sahilrajput03 new discord link: https://discord.gg/XaEdCSPyNa

The readme was just messed up
