### ISSUE TITLE
Could the Windows method work on AMD processors?

### ISSUE THREAD

**Issue by kwyntes** [notAperson535/OneClick-macOS-Simple-KVM#32]
Apparently I made a mistake by buying an 5900X for things like this since it seems like Hyper-V doesn't really like AMD with nested virtualization / KVM and stuff or something, but is there a workaround for this?

The issue is that `kvm-ok` returns that my processor isn't supported, which I know isn't true since Ryzen processors do actually support virtualization.

If there's no workaround I'll try to run this inside of a VMware machine, and if that doesn't work I'll probably have to dual boot which is really inconvenient.

Sorry for asking such an uneducated question, so my apologies if it's a bit unclear.

**Comment by notAperson535** [comment]
@kwyntes did you make sure that the amd fixes are selected here: https://user-images.githubusercontent.com/95918679/152704984-213b067b-1a8e-45cf-ad23-330391c31583.png

**Comment by kwyntes** [comment]
I made sure the `KVM for AMD processors support` was selected with a little `<*>`.

I also tried it with the modularizing thing (so it is selected as `<M>`).

Also I noticed that when the dialog window closed, the script told me to run `make`, which did not work as there was no `Makefile` created.

**Comment by kwyntes** [comment]
Yes, I enabled SVM in my BIOS (Asus motherboard). I can also confirm that VMware detects and allows me to use AMD-V/RVI.

**Comment by justinclift** [comment]
As a data point, I'm using a Ryzen 5600X (same generation as 5900X).  It's running this fine, though using Linux (Ubuntu 20.04) rather than Windows as the host OS.  Motherboard in my case is an ASRock [B550M Pro4](https://www.asrock.com/MB/AMD/B550M%20Pro4/index.asp).

**Comment by kwyntes** [comment]
@justinclift I know the problem definitely isn't caused by the hardware itself, as the processor absolutely supports nested virtualization and KVM and stuff. The issue here is that because this is running through WSL, Hyper-V has to be enabled on the host OS, which does not play nicely with Ryzen. I was wondering if there was any fix/workaround for this, as it was kind of suggested in the user guide for installing this on Windows that AMD CPUs are (or at least should be) supported.

**Comment by justinclift** [comment]
Ahhh, makes sense. :smile:

**Comment by Kyu** [comment]
Works perfectly up to Big Sur, Using a laptop, Ryzen4600H CPU with Raedon iGpu, and Radeon RX 5600 OEM/5600 XT dGpu. Idk why Monterey doesn't work but that's an issue for another time.

**Comment by notAperson535** [comment]
> > As a data point, I'm using a Ryzen 5600X (same generation as 5900X). It's running this fine, though using Linux (Ubuntu 20.04) rather than Windows as the host OS. Motherboard in my case is an ASRock [B550M Pro4](https://www.asrock.com/MB/AMD/B550M%20Pro4/index.asp).
> 
> @justinclift I know the problem definitely isn't caused by the hardware itself, as the processor absolutely supports nested virtualization and KVM and stuff. The issue here is that because this is running through WSL, Hyper-V has to be enabled on the host OS, which does not play nicely with Ryzen. I was wondering if there was any fix/workaround for this, as it was kind of suggested in the user guide for installing this on Windows that AMD CPUs are (or at least should be) supported.

@kwyntes I was not aware that hyper-v did not like ryzen. I would suggest searching up the answer, because I have no idea.

**Comment by Medizinmann-MD** [comment]
Did you make sure you are on the latest Window 10 Pro or Windows 11 Pro build?

Did you try to build a Custom Kernel first?

https://boxofcables.dev/kvm-optimized-custom-kernel-wsl2-2022/
https://forum.level1techs.com/t/windows-10-wsl2-enable-kvm-nested-virtualisation-on-amd/179072

**Comment by notAperson535** [comment]
@kwyntes Try using windows 11 if not already.

> *AFAIK only insider builds of Windows 10 Pro support nested virtualization for AMD! Safest bet is Windows 11 Pro!

**Comment by kwyntes** [comment]
> Did you make sure you are on the latest Window 10 Pro* or Windows 11 Pro build?
> 
> Did you try to build a Custom Kernel first?
> 
> https://boxofcables.dev/kvm-optimized-custom-kernel-wsl2-2022/
> https://forum.level1techs.com/t/windows-10-wsl2-enable-kvm-nested-virtualisation-on-amd/179072
> 
> *AFAIK only insider builds of Windows 10 Pro support nested virtualization for AMD! Safest bet is Windows 11 Pro!

Right, thanks for the answer. I was running Windows 10 and I'd rather not upgrade to 11. I'll just dual boot Linux and try it on there instead then.
