### ISSUE TITLE
KVM extensions not supported 

### ISSUE THREAD

**Issue by Abzl0** [notAperson535/OneClick-macOS-Simple-KVM#34]
I'm trying to install Monterey on windows but when I get to the point where I have to check if the KVM actually works in wsl it comes back as your cpu does not support KVM extensions. I've ran KVM on the same PC before on different distros on bare metal but never had this issue. Cpu i5-3320m (I have all virtualization settings enabled in bios)

**Comment by notAperson535** [comment]
@Abzl0 try removing wsl from the computer and then running `wsl --install` in the terminal.

**Comment by Abzl0** [comment]
I reinstalled windows, then did wsl.exe --install because wsl --install didn't directly install it, then i restarted and it gave me an error to get the new kernel, after i got the new kernel i proceeded with all the steps but i get the exact same error.

**Comment by Abzl0** [comment]
I turned off hyper-v and now kvm extensions are supported, but I still get an error saying module kvm_intel not found

**Comment by Abzl0** [comment]
I've tried soo much solutions but I couldn't get this to work on windows 10, i bypassed tpm and got windows 11 and it works flawlessly. I'm really not sure why windows 10 wasn't working but when i was researching I did find some stuff that are limited in windows 10 WSL. Thought this might be helpfull.
