### ISSUE TITLE
Vs Code is not working in Bigsur

### ISSUE THREAD

**Issue by Harismehmoodulhaq** [notAperson535/OneClick-macOS-Simple-KVM#36]
I install Bigsur
And I need Vscode in bigsur for my office work but when i install vscode and start its not working fine not Complete Ui laggy and so on
Please help me how to resolve this Tanks

**Comment by notAperson535** [comment]
@Harismehmoodulhaq how did you fix this?

**Comment by Harismehmoodulhaq** [comment]
I am not able to fix it yet i closed it and make a new request you answer me 
Vs Code not working in MacOS BigSur #37

**Comment by jstdk** [comment]
It works (for me) if you use 'code --disable-gpu'
