### ISSUE TITLE
Vs Code not working in MacOS BigSur

### ISSUE THREAD

**Issue by Harismehmoodulhaq** [notAperson535/OneClick-macOS-Simple-KVM#37]
I install Bigsur
And I need Vscode in bigsur for my office work but when i install vscode and start its not working fine not Complete Ui laggy and so on
Also BigSur Run but laggy
![image](https://user-images.githubusercontent.com/62013579/193034047-22cbbbce-2016-408e-b769-4cee0eeb963f.png)

Please help me how to resolve this Tanks

**Comment by notAperson535** [comment]
@Harismehmoodulhaq try passing through your gpu or just using https://vscode.dev

**Comment by Harismehmoodulhaq** [comment]
can you please guide me how to pass through my gpu in ubuntu

**Comment by jstdk** [comment]
or use 'code --disable-gpu'
