### ISSUE TITLE
ERROR When Passing GPU Passthrough in ubuntu

### ISSUE THREAD

**Issue by Harismehmoodulhaq** [notAperson535/OneClick-macOS-Simple-KVM#38]
Using this command 

iommu=pt intel_iommu=on vfio-pci.ids=1002:66af,1002:ab20

Error 

![image](https://user-images.githubusercontent.com/62013579/193215170-6d090eae-5ead-4d56-97ce-f58aad1f53df.png)

**Comment by notAperson535** [comment]
@Harismehmoodulhaq Those are the kernel commands you put in grub or similar.
