### ISSUE TITLE
qxl_send_events: spice-server bug: guest stopped, ignoring

### ISSUE THREAD

**Issue by KayTaneJupiter** [notAperson535/OneClick-macOS-Simple-KVM#42]
OpenSUSE Tumbleweed

./basic.sh

warning: short-form boolean option 'readonly' deprecated
Please use readonly=on instead
qxl_send_events: spice-server bug: guest stopped, ignoring
gtk initialization failed

**Comment by CryptoMinerAndriod** [comment]
I have seen this before, also IDK why VNC breaks mouse/trackpad input...

**Comment by notAperson535** [comment]
@KayTaneJupiter Sorry for the late reply, but you should be able to remove this line from `basic.sh`

```
-vga qxl \
```
