### ISSUE TITLE
Why Extended Journaled instead of APFS?

### ISSUE THREAD

**Issue by sharpordie** [notAperson535/OneClick-macOS-Simple-KVM#45]
Why do you advise to use macOS Extended Journaled to format the hard disk instead of APFS?

**Comment by meow464** [comment]
Also curious.

**Comment by therealrem** [comment]
I used APFS without problem ;-)

**Comment by notAperson535** [comment]
I'm actually not sure the technical reasons of why. It just seems to work and APFS just doesn't. Sorry for the wait for this not very helpful comment.
