### ISSUE TITLE
Improvements bridged network guide

### ISSUE THREAD

**Issue by meow464** [notAperson535/OneClick-macOS-Simple-KVM#46]
Please specify that in the netctl settings the device name should go inside the parenthesis (DEVICENAME). I thought you were supposed to remove the parenthesis and just write the device name. There is no clear error message for this.

https://oneclick-macos-simple-kvm.notaperson535.is-a.dev/docs/guide-networking/#attach-bridge-to-qemu

**Comment by meow464** [comment]
On Debian you need to set uid to the qemu-bridge-helper or call qemu as root. Maybe adding your user to the kvm group will work too.

```
sudo chmod 4755 /usr/lib/qemu/qemu-bridge-helpe
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765936

**Comment by meow464** [comment]
Btw the default network setup didn't work for me, I still don't know why. Debian 11.

**Comment by notAperson535** [comment]
@meow464 could you turn this into a PR?

**Comment by meow464** [comment]
I didn't find the repo for the docs :(

**Comment by notAperson535** [comment]
@meow464 it's the `docs` branch of this repo
