### ISSUE TITLE
Feature Request: Enabling Bluetooth in VM

### ISSUE THREAD

**Issue by schmurian** [notAperson535/OneClick-macOS-Simple-KVM#52]
**Is your feature request related to a problem? Please describe.**
In order to pair other apple devices, it would be nice to have Bluetooth available in the VM.

**Describe the solution you'd like**
Forward Bluetooth through a bridge? Or assign the user/group to the VM? (Sorry, I don't know what exactly is necessary to make this work)

**Describe alternatives you've considered**
None so far.

**Additional context**
Just started with macOS Catalina on a AMD linux system and it's awesome! Thank you for this easy way of installing macOS.

**Comment by notAperson535** [comment]
@schmurian I am not sure how this would work. You could try to pass your Bluetooth card through to the vm.
