### ISSUE TITLE
[docs] Add External GPU support guide for WSLG or GWSL

### ISSUE THREAD

**Issue by prateekmedia** [notAperson535/OneClick-macOS-Simple-KVM#57]
Currently the docs are written keeping linux in mind but gpu support is also need in wsl method.

The problem is that the doc states pci port number but in the case of gwsl or wsl this is not constant so we cannot have it in kernel parameter in where vfio pci id's are placed 

Same goes for VNC viewer, it don't have any docs for that

**Comment by notAperson535** [comment]
@prateekmedia I am not sure that you can pass through gpus in WSL. If there is a way, please tell me, but from my understanding, you can't

**Comment by prateekmedia** [comment]
WSL does support gpu acceleration but I don't have a passthrough guide available.

**Comment by notAperson535** [comment]
> WSL does support gpu acceleration but I don't have a passthrough guide available.

I found one, and can give it to you by the end of the week.

**Comment by prateekmedia** [comment]
@notAperson535 Any update on this?

**Comment by notAperson535** [comment]
@prateekmedia Yes actually, one my my discord server members found it: https://mathiashueber.com/passthrough-windows-11-vm-ubuntu-22-04/
