### ISSUE TITLE
High Serria kernel panics.

### ISSUE THREAD

**Issue by CryptoMinerAndriod** [notAperson535/OneClick-macOS-Simple-KVM#58]
when I tried to install MacOS High Sierra, it kernel panics, my device is a Sony VAIO, with a dual core athlon, p.s I have a 27GB SWAP partition OS: Debian 11.5 (amd64), steps to reproduce download High Sierra's DMG, then turn it into an img, then try to install, should I use another MacOS version?

**Comment by CryptoMinerAndriod** [comment]
spamming MACH reboot...

**Comment by CryptoMinerAndriod** [comment]
downloading MacOS Big Sur instead

**Comment by CryptoMinerAndriod** [comment]
none works!, oh and it's because it's saying Host Does not support requested feature for most features

**Comment by notAperson535** [comment]
> oh and it's because it's saying Host Does not support requested feature for most features

What kind of machine hardware do you use?

**Comment by CryptoMinerAndriod** [comment]
> > oh and it's because it's saying Host Does not support requested feature for most features
> 
> What kind of machine hardware do you use?

A Sony VAIO with an AMD k10 CPU (dual core athlon), I do have an Atom based tablet, but it's battery drains too quick

**Comment by CryptoMinerAndriod** [comment]
the mouse won't move in opencore

**Comment by CryptoMinerAndriod** [comment]
> > > oh and it's because it's saying Host Does not support requested feature for most features
> > 
> > 
> > What kind of machine hardware do you use?
> 
> A Sony VAIO with an AMD k10 CPU (dual core athlon), I do have an Atom based tablet, but it's battery drains too quick

I replaced KVM with TCG (multi)

**Comment by CryptoMinerAndriod** [comment]
> 

with an AMD system on KVM

**Comment by notAperson535** [comment]
> the mouse won't move in opencore

@CryptoMinerAndriod Yeah it doesn't move in OpenCore

**Comment by CryptoMinerAndriod** [comment]
> > the mouse won't move in opencore
> 
> @CryptoMinerAndriod Yeah it doesn't move in OpenCore

Ok I have an AMD FX-8310 PC with no PSU and RAM atm

**Comment by CryptoMinerAndriod** [comment]
Oops pressed wrong button

**Comment by notAperson535** [comment]
Think this is fixed
