### ISSUE TITLE
Big Sur headless installation stuck

### ISSUE THREAD

**Issue by mrmartan** [notAperson535/OneClick-macOS-Simple-KVM#59]
EDIT: sry for not being able to give it a better title

**Which operating system are you trying to install?**
macOS Big Sur

**Describe the bug**
Stuck on the macOS installation/configuration screen. The guide says to be patient at this stage of the process (with about 1 minute remaining), but it is like this for two hours. The CPU and RAM consumption on the host also dropped to almost 0.

**To Reproduce**
HEADLESS=1 ./basic.sh
Went through the disc partitioning and mac installation utility, performed the first stage of the installation while rebooting a few times, now it is running from the "Macintosh Disk"

**Screenshots**

![image](https://user-images.githubusercontent.com/2376580/205688587-fce36f93-6263-41c4-8c35-ed0e817f71ad.png)  

![image](https://user-images.githubusercontent.com/2376580/205688688-859f8a9e-bea3-4e83-95b7-63d560ad1240.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22

The host linux is VM running on VMWare

![image](https://user-images.githubusercontent.com/2376580/205689030-ab44cf8b-e03d-4911-a190-34e3d88cec85.png)

**Comment by notAperson535** [comment]
@mrmartan Why are you using VMWare? And do you have cpu acceleration and virtualization enabled in VMWare?
