### ISSUE TITLE
Opencore visually glitched

### ISSUE THREAD

**Issue by hockeymikey** [notAperson535/OneClick-macOS-Simple-KVM#6]
![Screenshot_20220211_080737](https://user-images.githubusercontent.com/1435185/153606327-d19cbc1b-414e-4f4b-9614-cece2542904f.png)

It works fine, but visually is glitched. How do I fix it? And enable auto selection of a drive after X seconds

**Comment by notAperson535** [comment]
@hockeymikey I am trying to figure out why it is glitched, but it should auto-select the main drive after a little bit.

**Comment by hockeymikey** [comment]
It defaults to the base system drive rather than excess, the main drive.

**Comment by hockeymikey** [comment]
It defaults to the base system drive rather than excess, the main drive.

**Comment by notAperson535** [comment]
@hockeymikey have you installed macOS yet?

**Comment by hockeymikey** [comment]
@notAperson535 Yes I have. I actually upgraded from Catalina which was using foxlet's branch. But that issue can be seen without that drive attached on a fresh clone of the repo.

**Comment by notAperson535** [comment]
@hockeymikey just updated the readme to fix this problem, it says to run basic-no-installer.sh instead of basic.sh, tell me if it works. You may need to update your version with `git pull --rebase`

**Comment by hockeymikey** [comment]
@notAperson535 Thanks for that. I'm using virt-man personally, but I see what you're saying in there just removing the installer drive. Any idea on the visual glitch? Maybe it's a me issue, granted Clover never had any issues I guess. I mean an Omen 15 2020 running Arch + kde if that helps (probably doesn't).

**Comment by notAperson535** [comment]
@hockeymikey I think it is something to do with the display type, I am trying to fix that now.

**Comment by notAperson535** [comment]
@hockeymikey I just discovered it selects the drive automatically after 45 seconds

**Comment by notAperson535** [comment]
@hockeymikey Fixed!

**Comment by hockeymikey** [comment]
> @hockeymikey Fixed!

Thank you for the hard work! What was the issue?

**Comment by notAperson535** [comment]
@hockeymikey the OVMF stuff

**Comment by hockeymikey** [comment]
> @hockeymikey the OVMF stuff

Cool. Confirmed good on my side too!

**Comment by notAperson535** [comment]
@hockeymikey how did you update?

**Comment by notAperson535** [comment]
> And enable auto selection of a drive after X seconds

You can enable it with instructions from here
```
Once macOS is succesfully installed, you can select the macOS partition with ctrl+enter to set it as the default boot and automatically boot up the VM without the macOS Installer attached. This will prevent OpenCore from default booting the installer.
```
