### ISSUE TITLE
Ventora Installer failed at applying update

### ISSUE THREAD

**Issue by funjay** [notAperson535/OneClick-macOS-Simple-KVM#62]
OS
macOS Ventura

**Describe the bug**
Macos installer runs to about 16 minutes more and the apple logo disapears and the next screen is "failed to apply update" at update assistance

**To Reproduce**
On Laption with WIFI, (dont know if this matters)
Host machine  = Fedora
Qemu version = QEMU emulator version 7.0.0 (qemu-7.0.0-12.fc37)
manual installation so i can increase the disk to 90gb and i used defaults including the disk name
Runs the first 2hrs counting and restarts
selected MacOs installer 
failed at applying updates

**Expected behavior**
To complete the installation

**Screenshots**
![image](https://user-images.githubusercontent.com/66911451/209990963-48cafc72-5696-4086-94a2-b40a221e5718.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Version QEMU emulator version 7.0.0 (qemu-7.0.0-12.fc37)

**Comment by notAperson535** [comment]
@funjay Please open the log, by going to "Window" in the topbar, and click show log or something like that. Make sure to select "show all logs"

**Comment by funjay** [comment]
magically it worked. I started it again hoping to re produce it, but  not errors. 
I didnt do anything after it happened more thn 4 times yesterday
my only theory could be apple server was down yesterday

thanks

**Comment by notAperson535** [comment]
@funjay Strange, but great for you! Glad you got it fixed.

**Comment by funjay** [comment]
Tried to do the apple ID fix but the EFI mounts and cant see any file, ( i feel it is because i used the APFC) started all over again with journaled and the issue is back

in the window menu , there is no show logs, image below

![image](https://user-images.githubusercontent.com/66911451/210133085-57bec899-8c8a-4db5-af36-4ca5a11b226e.png)

**Comment by notAperson535** [comment]
@funjay Sorrry, I think you have to click "view", just look through all the menu bar entries

**Comment by funjay** [comment]
nothing showing logs

1.  click on reinstall mac
2. it loads (after the utility steps) from 2hrs to 12 mins and stays long at 12mins
3. then it restarts and has two options, the base and the install mac , it loads the install mac and starts from 29 mins counting down
4. at about 18mins it shows that error and that window, there is no place to show logs.. 

the show logs is at the first installer loads

at the 12mins before the restart i find this

![image](https://user-images.githubusercontent.com/66911451/210147428-7042fe9b-7ad4-4d98-a145-7300a0d88807.png)

**Comment by notAperson535** [comment]
@funjay make sure to format as macOS extended journaled and make sure you have a stable internet connection.

**Comment by funjay** [comment]
i see this also 

![image](https://user-images.githubusercontent.com/66911451/210147903-6abbeb3c-f142-42f4-8ca1-02ea0448931c.png)

format is extended journaled and it didnt work (8 times, it kept adding data to the disk name anytime i retried)
i decided to use the other one to see if that was the magic yesterday and u online, i guess that didnt change
i have a very fast internet and stable ( i use a FTTH)

**Comment by notAperson535** [comment]
@funjay try reformatting the Qemu disk in disk utility, and try again

**Comment by funjay** [comment]
Yes i dont get the extended journal option when i try reformating it.  Tried this already though and it is the same. Some times recreate the qemu disk and i get the extended journal . 

i feel it is my hard disk issue, i use an SSD on fedora ? does that ring a bell
can i try pre allocating the size when creating the disk instead of dynamic allocation? i guess the speed of the expansion vs need? a race condition?

is it possible to preallocate the size when creating the image?

**Comment by notAperson535** [comment]
@funjay ij terms of not seeing the macOS extended journaled option, click the drop-down in the top left of disk utility and click on show all devices. Then select the largest disk around 64gbs if that’s what you allocated, and then you can format it

**Comment by funjay** [comment]
fingers crossed
Restarted the process
created the disk preallocated 90G
formatted with extended journaled 
currently running first stage.

**Comment by notAperson535** [comment]
Ok, let’s see

**Comment by funjay** [comment]
Good news it worked

the 12mins this time didnt take long
![image](https://user-images.githubusercontent.com/66911451/210150108-3a3e9d66-c66e-4cf5-9173-29ac6dcfe94d.png)

the message is different at 12mins remaining
finally worked , installation completed

thanks

Something to explore, why did the disk keep failing for dynamic allocation vs preallocation. is my physical disk getting bad?

**Comment by funjay** [comment]
Many thanks for your time and assistance. 

Happy New year!

**Comment by notAperson535** [comment]
> Many thanks for your time and assistance. 
> 
> 
> 
> Happy New year!

@funjay You too! Glad you got this fixed.
