### ISSUE TITLE
Do the same thing but ISO for PC.

### ISSUE THREAD

**Issue by itayalush** [notAperson535/OneClick-macOS-Simple-KVM#66]
Please make same thing but with macOS and OpenCore ISO that you flash into a USB and the whole Hackintosh is ready and working.
That'll solve all of the problems with creating a Hackintosh, It will be much easier.

**Comment by notAperson535** [comment]
@itayalush Hackintoshing doesn't exactly work like that. Every machine is different and requires different configurations. If you want to hackintosh, you can follow this great guide by dortania:
https://dortania.github.io/OpenCore-Install-Guide/
