### ISSUE TITLE
Could not access KVM kernel module

### ISSUE THREAD

**Issue by Exohayvan** [notAperson535/OneClick-macOS-Simple-KVM#69]
**Which operating system are you trying to install?**
Ventura (13)

**Describe the bug**
Received the following error after downloading OS.

No protocol specified
Unable to init server: Could not connect: Connection refused
Could not access KVM kernel module: No such file or directory
qumu-system-x86_64: failed to initialize kvm: No such file or directory

**To Reproduce**
1. Run setup.py
2. Enter the version
3. Wait till after it downloads

**Expected behavior**
Set up KVM

**Desktop (please complete the following information):**
 - OS: Chrome OS (version 108.0.5359.127)
 - Linux Container: Debian GNU/Linux 11 (bullseye)
 - Kernel: 5.10.147.20159-g06a9a2b12b31

**Comment by notAperson535** [comment]
@Exohayvan make sure all of the dependencies are installed correctly and make sure virtualization is enabled in the BIOS

**Comment by Exohayvan** [comment]
Dependencies are installed correctly, I even uninstalled them and reinstalled. 

Have not looked to see if virtualization was enabled, will check the next moment I can.
