### ISSUE TITLE
virsh create template.xml --> Network not found

### ISSUE THREAD

**Issue by Slapbox** [notAperson535/OneClick-macOS-Simple-KVM#7]
After `sudo ./make.sh --add` I get errors related to the `template.xml` containing the wrong path to the QEMU binary. After correcting that I tried running `virsh create template.xml` but I see:

```
error: Network not found: no network with matching name 'default'
```

Any ideas?

**Comment by Slapbox** [comment]
Got it working, perhaps by starting a blank virtual machine first to bring the network interface up. Really not sure, too noob.

**Comment by notAperson535** [comment]
@Slapbox glad you fixed it! Any ideas on how I could add this to the readme?

**Comment by Slapbox** [comment]
Unfortunately not - too noob to really know for sure how it was even made to work.

I think it worked because `virt-manager` would automatically bring up the `default` network interface when a machine was booted - but I believe there was a checkbox that needed to be checked for that to occur.
