### ISSUE TITLE
It takes forever to install.

### ISSUE THREAD

**Issue by itayalush** [notAperson535/OneClick-macOS-Simple-KVM#70]
Hi, I'm trying to install macOS on KVM on my laptop, it takes forever to install! It was stuck at 2 hours and 17 minutes left, and now it's 4 hours and 28 minutes!!
How do I fix this?

**Comment by itayalush** [comment]
Do you remember me?

**Comment by itayalush** [comment]
Oh I just opened the Installer log, maybe it will finish sooner and I will see it on the log, but it will still say "Infinite time remaining".

**Comment by notAperson535** [comment]
@itayalush Just let it install overnight, it takes forever.
