### ISSUE TITLE
Bug Report : Cannot install in opensuse tumbleweed

### ISSUE THREAD

**Issue by linuxneggs** [notAperson535/OneClick-macOS-Simple-KVM#72]
**Which operating system are you trying to install?**
macOS Big sur

**Describe the bug**
I have this error when trying to run the oneclick installer for opensuse:

qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
gtk initialization failed

**Desktop (please complete the following information):**
 - OS: opensuse tumbleweed
 - Version: The latest

**Comment by notAperson535** [comment]
@linuxneggs You must remove this line from basic.sh, and then run `./basic.sh`
```bash
    -vga qxl \
```
I think it's line 27

**Comment by linuxneggs** [comment]
@notAperson535  its not that i have the same error

**Comment by notAperson535** [comment]
@linuxneggs Try running it headless `HEADLESS=1 ./basic.sh`

**Comment by linuxneggs** [comment]
@notAperson535  it display
 BdsDxe: loading Boot0001 "UEFI QEMU HARDDISK QM00017 " from PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x2,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU HARDDISK QM00017 " from PciRoot(0x0)/Pci(0x4,0x0)/Sata(0x2,0xFFFF,0x0)
OCS: No schema for Arch at 0 index, context <Add>!
OCS: No schema for BundlePath at 1 index, context <Add>!
OCS: No schema for ExecutablePath at 4 index, context <Add>!
OCS: No schema for MaxKernel at 5 index, context <Add>!
OCS: No schema for MinKernel at 6 index, context <Add>!
OCS: No schema for PlistPath at 7 index, context <Add>!
 
in the terminal and then it not do anything

**Comment by notAperson535** [comment]
@linuxneggs You have to connect to the vm using a vnc viewer. The vm is run on port 5900

**Comment by linuxneggs** [comment]
@notAperson535  it works but after formating the disk and try to install macos it tell me it will take 2 hours then 11 hours then 10 hours then 20 hours ....
is this normal ?

**Comment by notAperson535** [comment]
@linuxneggs Yes, it takes forever

**Comment by bigc0127** [comment]
> @linuxneggs You must remove this line from basic.sh, and then run `./basic.sh`
> 
> ```shell
>     -vga qxl \
> ```
> 
> I think it's line 27

Worked for me, thank you!

**Comment by bigc0127** [comment]
> @linuxneggs You must remove this line from basic.sh, and then run `./basic.sh`
> 
> ```shell
>     -vga qxl \
> ```
> 
> I think it's line 27

Worked for me!

thank you @notAperson535

**Comment by notAperson535** [comment]
Glad it worked!
