### ISSUE TITLE
"Couldn't alloc class applekeystoretest" when installing Ventura

### ISSUE THREAD

**Issue by kingsvell** [notAperson535/OneClick-macOS-Simple-KVM#75]
**Which operating system are you trying to install?**
e.g. macOS Ventura

**Describe the bug**
When i try to simple open the BaseSystem file, it runs to certain point that gives me that error: "couldn't alloc class applekeystoretest"

**To Reproduce**
1. Select and click baseSimstem in  OpenCore and go directly to the error.

**Expected behavior**
Go through the verbose until start the recovery mode

**Desktop (please complete the following information):**
 - OS: ArchLInux
 - Linux archlinux 6.2.10-arch1-1
 - Ryzen 7 5700g

In my reasearch: 
"-cpu Haswell,vendor=GenuineIntel" is a must, i dont know if this could cause performance issues....
" -smp cores=4,threads=2,sockets=1" - more than that the BaseSystem wont open

**Comment by notAperson535** [comment]
@kingsvell for the cpu haswell part you can change it to cpu host

**Comment by Thomas-Jld** [comment]
I have the same issue but using one core and one thread allows me to go through the installation, which doesn't really help because the performances are horrible...

**Comment by hockeymikey** [comment]
![Screenshot_20230509_095332](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/1435185/f92ec17d-9a89-4c98-95bf-9d2e45c8e64a)
Recovery gets locked up here on 1core
