### ISSUE TITLE
My macOS Setup stuck on 30hours

### ISSUE THREAD

**Issue by neondev27** [notAperson535/OneClick-macOS-Simple-KVM#83]
I think my internet is good, but installation is says 30 hours left to finish install.

**Comment by notAperson535** [comment]
Just wait overnight, this is pretty normal

**Comment by neodev27** [comment]
OK, I'll check and let you know later

**Comment by neodev27** [comment]
I wanna ask, will I need to run basic.sh for start my machine everytime?

**Comment by notAperson535** [comment]
Yes

**Comment by clauderobi** [comment]
No, you can use virt-manager.

**Comment by notAperson535** [comment]
Yeah either or works
