### ISSUE TITLE
Ventura install freezes/panics

### ISSUE THREAD

**Issue by hockeymikey** [notAperson535/OneClick-macOS-Simple-KVM#84]
**Which operating system are you trying to install?**
Ventura

**Describe the bug**
Not able to install Ventura either on an existing Big Sur install or a new fresh install. You seem to get further in the boot install as seen in https://github.com/notAperson535/OneClick-macOS-Simple-KVM/issues/75 setting it to only 1 core and 1 thread, but it doesn't go all the way and freezes up (nor is 1 c/t what is desired.

**To Reproduce**
1. Do a fresh install
2. Freezes and reboots after some kernel panic or something

**Expected behavior**
Works like normal and does install

**Screenshots**
https://cloud.hockeymikey.com/index.php/s/6Mjy83rQZo4sQd5

https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/1435185/0863ca2a-0183-47a2-b2b6-a96065bf01a6

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Computer: Omen 15, 4800H with a RTX 2060

**Comment by notAperson535** [comment]
This may be due to an outdated OpenCore version, which I will fix this weekend

**Comment by hockeymikey** [comment]
@notAperson535 I don't think so, I compiled my own updating the version with on luck. I can experiment and try any ktexts that may help.

**Comment by hockeymikey** [comment]
Circling back to this, I have the same issues with Monterey I think. Seems it can go longer when I go down to 1 core, 1 thread but eventually gets stuck on a gray screen after it gets done loading. Tried on a new install too.

**Comment by hockeymikey** [comment]
So I made the jump to Sonoma, somehow. I think I did an in system upgrade, the I switched over to one core, one thread to finish the install. Then I made some modifications to get past the panics.
https://www.nicksherlock.com/2022/10/installing-macos-13-ventura-on-proxmox/comment-page-1/#comment-55532
I did not have TSC_ADJUST on my system. So I went to bios and disabled a battery optimization.
Added: "clocksource=tsc tsc=reliable" to GRUB_CMDLINE_LINUX_DEFAULT.
Added +tsc_adjust to the cpu parameters. 
Then I added https://github.com/acidanthera/CpuTscSync to my opencore. These other links helped me too.

https://github.com/acidanthera/bugtracker/issues/1900
https://github.com/acidanthera/bugtracker/issues/2163
https://github.com/acidanthera/bugtracker/issues/1944

**Comment by notAperson535** [comment]
> Then I added https://github.com/acidanthera/CpuTscSync to my opencore.

With newer builds of this repo I have added the cputscsync

**Comment by hockeymikey** [comment]
@notAperson535 When did you add it in? You still use the preview branch for OC building, correct?

**Comment by notAperson535** [comment]
> @notAperson535 When did you add it in? You still use the preview branch for OC building, correct?

I don't use that branch anymore. Not sure exactly how long ago I updated it, maybe a few months ago

**Comment by hockeymikey** [comment]
@notAperson535 Which branch do you use for building OC?
