### ISSUE TITLE
macOS 13 doesn't pickup passedthrough mouse/keyboard input

### ISSUE THREAD

**Issue by Merc2D** [notAperson535/OneClick-macOS-Simple-KVM#87]
**Which operating system are you trying to install?**
macOS ventura 13

**Describe the bug**
Passedthrough Mouse/keyboard doesn't work in macOS 13

**To Reproduce**
Simply Launch macOS 13. Opencore bootpicker will pickup the mouse and keyboard correctly

**Expected behavior**
Pickup mouse and keyboard. I suspect it to be a opencore config issue 

**Desktop (please complete the following information):**
 - OS: fedora
 - Version 38

**Additional context**
This is run on single gpu passthrough via virt manager. Had no issues with other macOS versions (Catalina to Monterey)

**Comment by notAperson535** [comment]
@Merc2D Are you saying that mouse movement does not work in the opencore picker or in the actual macOS environment?

**Comment by Merc2D** [comment]
> 

macOS environment

**Comment by notAperson535** [comment]
So the mouse input is not working at all, or is it just offset really weirdly?

**Comment by Merc2D** [comment]
It's not working at all

**Comment by Merc2D** [comment]
The same also goas with keyboard except it works on the opencore boot menu and after that nothing works

**Comment by justinclift** [comment]
As a thought, are you using the qemu command line directly or are you using the VM after importing it into Libvirt / Virt-Manager?

If you're using it with Virt-Manager, then one potential solution is to try changing the USB mouse/keyboard type.  With the mouse at least, you can try adding a virtual "graphics tablet" instead which can sometimes fix the problem.  Not sure on the keyboard front though.

**Comment by Merc2D** [comment]
Hello I have tried the fix that you have mentioned and sadly it doesn't work, although thanks for the help and also I'm extremely sorry about the late response as I was busy with other stuff.

**Comment by justinclift** [comment]
You're using the VM with Libvirt yeah? :smile:

**Comment by Merc2D** [comment]
Yes indeed.

**Comment by Merc2D** [comment]
Yes indeed mate

**Comment by justinclift** [comment]
k, I've just started a VM here that has working input.  Looking at the configuration for it in virt-manager, it has these devices attached:

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/f13a7ad6-ee00-44ab-bc82-3e654a54c210)

That's showing 4 input devices:

* 1 Mouse
* 1 Tablet
* 2 Keyboards

Looking at the details for them in the GUI, they show:

### Mouse

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/e1a9801d-cd21-40c5-ab28-1d1279b7adc0)

### Tablet

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/9bc3e3cc-e8bb-4458-9cbe-b2c7bce347a7)

### First keyboard

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/c08bac80-ab9d-49d9-a3b4-70cace5bb8c2)

### Second keyboard

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/65d4ecd5-cdcc-4d6f-b342-8f5e0183674c)

Near the bottom on the device list there is also a `Controller USB 0`.

It's currently set to USB 2:

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/7c9e8bd3-c550-4f13-8a01-53faf565ff30)

At the very bottom of the device list there are also 2 "USB Redirectors".

They're set to:

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/0a1636a2-0d2e-4ea9-aec8-5ccd3d121560)

and

![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/406299/7fea696f-3e60-47a1-be32-46f131e74f3e)

Maybe see if matching those settings works.  If it doesn't, I can provide my Libvirt XML configuration file which you could cut-n-paste.

**Comment by Merc2D** [comment]
Yeah sadly that didn't work, although thanks for the help and the detailed instructions

**Comment by Merc2D** [comment]
Here is my xml if you want to take a look at it[My xml](https://pastebin.com/YeqtBMgD)

**Comment by justinclift** [comment]
Meh, I'm too tired to take a look at it right now.  This is mine if it helps.  I've only changed the paths in it to have a `PATH_TO` token instead.

[macos_libvirt_myworking.txt](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/files/11782862/macos_libvirt_myworking.txt)

As this is a "known good" xml, I'd recommend updating the paths in that file to point to your firmware file, settings file, and macOS files.  With that it *should* in theory work.  Hopefully. :smile:

**Comment by justinclift** [comment]
These are the OVMF firmware and settings I'm using too (compressed into a tarball), which might be useful to use with it as well.  Just to maximise your chances of it going ok. :smile:

[OVMF_firmware_and_settings.tar.gz](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/files/11782867/OVMF_firmware_and_settings.tar.gz)

**Comment by Merc2D** [comment]
I have been to

> Meh, I'm too tired to take a look at it right now. This is mine if it helps. I've only changed the paths in it to have a `PATH_TO` token instead.
> 
> [macos_libvirt_myworking.txt](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/files/11782862/macos_libvirt_myworking.txt)
> 
> As this is a "known good" xml, I'd recommend updating the paths in that file to point to your firmware file, settings file, and macOS files. With that it _should_ in theory work. Hopefully. 😄



I have been trying to get USB working on this xml for 4 days straight yet sadly nothing worked...😔  And I've lost all hope at this point although still many thanks for you mate

**Comment by notAperson535** [comment]
@Merc2D turn off gpu pass through temporary. I've heard of it causing issues before

**Comment by justinclift** [comment]
Probably worth a shot, just to see if it works. :smile:

**Comment by notAperson535** [comment]
@Merc2D were you ever able to resolve the issue?

**Comment by jpfleischer** [comment]
this https://github.com/notAperson535/OneClick-macOS-Simple-KVM/pull/105 probably solves it. should close

**Comment by notAperson535** [comment]
That's a different issue, but since theres been no response for some time I am closing the issue.
