### ISSUE TITLE
GCP

### ISSUE THREAD

**Issue by john-peterson** [notAperson535/OneClick-macOS-Simple-KVM#89]
![Screenshot_20230623-072738](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/207571/fa61eb24-8aca-40b6-a727-cd880c6909d3)

```
gcloud compute instances create mac --provisioning-model spot --scopes https://www.googleapis.com/auth/devstorage.full_control --boot-disk-size 200 --enable-nested-virtualization --machine-type n1-standard-8 --image-project ubuntu-os-cloud --image-family ubuntu-minimal-2304-amd64 --boot-disk-type pd-balanced

sudo apt install apt-file qemu-system-x86 qemu-utils dmg2img git htop screen nano

```

**Comment by john-peterson** [comment]
![Screenshot_20230623-082349](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/207571/7ece283e-d60b-42c0-b623-52239eb5a632)

```
cat /volumes/untitled/var/log/install.log
```

**Comment by john-peterson** [comment]
Stumped in reading the log outside in normal text. Input appreciated

```
sudo modprobe nbd max_part=8
sudo qemu-nbd --connect=/dev/nbd0 macOS.qcow2
sudo fdisk /dev/nbd0 -l
sudo fsapfsinfo /dev/nbd0p2
sudo fsapfsmount -f 4 /dev/nbd0p2 /mnt/mac

```

**Comment by notAperson535** [comment]
> ![Screenshot_20230623-072738](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/207571/fa61eb24-8aca-40b6-a727-cd880c6909d3)
> 
> 
> 
> ```
> 
> gcloud compute instances create mac --provisioning-model spot --scopes https://www.googleapis.com/auth/devstorage.full_control --boot-disk-size 200 --enable-nested-virtualization --machine-type n1-standard-8 --image-project ubuntu-os-cloud --image-family ubuntu-minimal-2304-amd64 --boot-disk-type pd-balanced
> 
> 
> 
> sudo apt install apt-file qemu-system-x86 qemu-utils dmg2img git htop screen nano
> 
> 
> 
> ```

Same thing happened to me. Try getting an offline installer for ventura like an iso.

**Comment by john-peterson** [comment]
I don't immediately understand the procedure. This should work. I am again stumped by getting the log

```
dev@mac:~$ sudo tree -a hfs                   hfs                                           ├── .HFS+ Private Directory Data\x0d          ├── .fseventsd                                │   └── fseventsd-uuid                        ├── .journal                                  ├── .journal_info_block                       ├── macOS Install Data                        │   ├── InstallAssistant.pkg.integrityDataV1  │   ├── InstallAssistant.pkg.partial          │   ├── Locked Files                          │   │   ├── .disk_label                       │   │   ├── .disk_label.contentDetails        │   │   ├── .disk_label_2x                    │   │   └── Boot Files                        │   └── index.sproduct                        └── ␀␀␀␀HFS+ Private Data                                                                   7 directories, 9 files                        dev@mac:~$
```

**Comment by notAperson535** [comment]
I think the way the newest ventura installer grabs files from online is different then before. Try Monterey first

**Comment by notAperson535** [comment]
> Stumped in reading the log outside in normal text. Input appreciated
> 
> 
> 
> ```
> 
> sudo modprobe nbd max_part=8
> 
> sudo qemu-nbd --connect=/dev/nbd0 macOS.qcow2
> 
> sudo fdisk /dev/nbd0 -l
> 
> sudo fsapfsinfo /dev/nbd0p2
> 
> sudo fsapfsmount -f 1 /dev/nbd0p2 /mnt/mac
> 
> ```
> 
> 
> 
> That corresponds to
> 
> 
> 
> ```
> 
> 
> 
> ls /volumes/untitled\ 1
> 
> 
> 
> ```
> 
> In the recovery boot ??? !  ??
> 
> 
> 
> /Volumes/untitled is the actual content but I don't know how it magically conjures that mount. Any insight appreciated 
> 
> 
> 
> It doesn't have many commands to help
> 
> 
> 
> ```
> 
> findmnt /volumes/untitled
> 
> Command not found
> 
> ```

This might be the opencore disk.

**Comment by notAperson535** [comment]
If you want to open the installer log press "window" in the top bar and select "installer log"

**Comment by john-peterson** [comment]
Maybe I can be so snyde as to ask for a Ventura image. Pre installed. There was one on vagrant but alas, parallels only :-[

```
vagrant box add logantbond/ventura
vagrant box list
It was a pre installed parallels image :-\
```

**Comment by notAperson535** [comment]
I do have offline installers but they're 15 gigs so I don't know how to share em.

**Comment by notAperson535** [comment]
Just search up "ventura iso" on Google and it'll be there. But do not share links here please. I don't wanna get this repo taken down.

**Comment by john-peterson** [comment]
So there is NO OFFICIAL OFFLINE INSTALLER? How are they created? What about `InstallAssistant.pkg`. There is no way to mount that in qemu?

**Comment by notAperson535** [comment]
@john-peterson apple is dumb. for a 100% official installer, u need a mac. If you know any online service that can host a 15gb file, I can make an offline installer for you, since I have a mac I can use.

**Comment by maurhub** [comment]
Just for the record, trying to install ventura using setupArch.sh throws the same error to me.

```OSISHelperProxy blessUpdateBundleAtPath:mutableProductPath:enclosingMountPoint:]_block_invoke_2: Error Domain=NSCocoaErrorDomain Code=260 "The file “bootbase.efi” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Volumes/Mac SSD/macOS Install Data/UpdateBundle/AssetData/./boot/Firmware/System/Library/CoreServices/bootbase.efi, NSUnderlyingError=0x600002df8930 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}```

I took this from other thread but the error is exaclty the same. Monterey installs ok.

So to update Ventura you need to get an ISO, you won't be able to do it via script right?

**Comment by notAperson535** [comment]
Sadly it seems the answer for that is yes.
