### ISSUE TITLE
Setup fails repeatedly without a hint where to start debugging

### ISSUE THREAD

**Issue by philippdieter** [notAperson535/OneClick-macOS-Simple-KVM#9]
I have the problem that the setup constantly fails. I don't even know if it really crashes or if it "just" reboots. Everything works fine until the 12 minute mark and suddenly the system reboots.

I tried to make some use of the install log but it's gone the moment the setup reboots, so I don't know to get info there.

I ran the setup on two different machines, both Intel i7. The system on both machines is arch, at the moment I don't have any other machine at hand. The systems are up to date. 

I tried with install images downloaded with fetch-macOS-v2.py, both Big Sur and Monterey and I tried a full Bug Sur installation medium generated on a mac, the result is always the same.

My main problem is that I don't know where else to look for information or what else to try. Any hint or help would be appreciated.

```
$ ./tools/debug.sh
== Distro Info ==
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
== Loaded Modules ==
kvm_intel             368640  0
kvm                  1069056  1 kvm_intel
irqbypass              16384  1 kvm
== Installed Binaries ==
QEMU emulator version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
virt-manager version 3.2.0
Python 3.10.2
pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)

$ cat /sys/module/kvm/parameters/ignore_msrs
Y
```

**Comment by notAperson535** [comment]
@philippdieter reinstall macOS, but open the Log menu and set the view to all. It is located in the menu bar under "windows" when inside the macOS installer

**Comment by philippdieter** [comment]
The problem with the log was, that it was gone the moment the machine reboots, so I was not able to read the last messages. I now just did a screenshot every second. Can you read something useful from the screenshot?

![2022-02-27-151848_1920x1080_scrot](https://user-images.githubusercontent.com/19897480/155890492-17674f6e-1ae9-4ce3-8a95-865dda88429b.png)

**Comment by sdasilva** [comment]
> The problem with the log was, that it was gone the moment the machine reboots, so I was not able to read the last messages. I now just did a screenshot every second. Can you read something useful from the screenshot?
> 
> ![2022-02-27-151848_1920x1080_scrot](https://user-images.githubusercontent.com/19897480/155890492-17674f6e-1ae9-4ce3-8a95-865dda88429b.png)

I just installed this on my Fedora AMD laptop. I formatted the HD as APFS. I was getting errors like you show.
I got a clean copy of the repo and started over, choosing Mac OS Extended Journeld. Installation of MacOS completed and the VM is working fine for me.

**Comment by notAperson535** [comment]
@philippdieter did you use macOS extended journaled or APFS? You need to use macOS extended journaled in disk utility, this is in the instructions

**Comment by philippdieter** [comment]
I used Journaled, but case-sensitive. It didn't came to my mind that this could have caused the trouble. I changed it and now the installation went fine. Thank you two very much!

**Comment by notAperson535** [comment]
You're welcome, thank you to @sdasilva for finding the issue!

**Comment by notAperson535** [comment]
> I used Journaled, but case-sensitive. It didn't came to my mind that this could have caused the trouble. I changed it and now the installation went fine. Thank you two very much!

just added this to the readme

**Comment by maurhub** [comment]
> 

Make sure the docs are properly referencing this, it says "NOT case-sensitive"
