### ISSUE TITLE
Fedora 38, AMD Ryzen cant boot into installer

### ISSUE THREAD

**Issue by samindaperamuna** [notAperson535/OneClick-macOS-Simple-KVM#93]
**Which operating system are you trying to install?**
BigSur

**Describe the bug**
Doesnt start the installer. Stops with the following screenshot.

**To Reproduce**
`sudo ./make.sh --add`
Open the VM in virt-manager
Add hard disks
Run VM

**Expected behavior**
Lets the user format disks and install MacOS

**Screenshots**
![cant_boot](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/16777956/03a3f8da-c2d0-429b-b34d-56382fe95c83)

**Desktop:**
 - OS: Fedora 38
 - AMD Ryzen 3600, RX 5600XT, 16GB DDR4

**Additional context**
Tried a couple of firmware and all give out the same error.

**Comment by Dravelz-21** [comment]
I get the same thing on every version, with verbose mode I get stuck at "matching deferred by IOUSBHostHIDDevice"

**Comment by notAperson535** [comment]
Same issue as #92 something to do with the kernel.

**Comment by samindaperamuna** [comment]
Can confirm it works on kernal 6.4.8-200.fc38.x86_64
