### ISSUE TITLE
Selecting 6 for Ventura actually downloads Sonoma

### ISSUE THREAD

**Issue by askiiart** [notAperson535/OneClick-macOS-Simple-KVM#95]
**Which operating system are you trying to install?**
macOS Ventura

**Describe the bug**

**To Reproduce**
1. Run setupArch.sh
2. Select Ventura with 6

**Expected behavior**
Ventura should be downloaded and run.

**Screenshots**
![image](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/assets/90910526/7c722d1b-c369-413a-a5db-32f05d52dd04)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
I don't think a cosmic ray flipped a bit, changing 6 to 7, but I suppose it's possible.

**Comment by notAperson535** [comment]
Are you on the latest version of the repository?

**Comment by askiiart** [comment]
@notAperson535 Yes, I had just cloned it.

**Comment by notAperson535** [comment]
Should be fixed with latest commit: f2cc760876f7503886f7f915e866e31f51a79e21

**Comment by Razzaline** [comment]
I know I'm not the original issue reporter, but as far as I can see, it seems to be correctly downloading Ventura now (I get an option to reinstall Ventura in the recovery program). Hopefully @askiiart can say if it's fixed for them too?

**Comment by notAperson535** [comment]
I'll just close the issue. Multiple server members have been downloading ventura, so I think it's fixed. Feel free to let me know if it's not @askiiart .
