### ISSUE TITLE
Screen resolution is much too large

### ISSUE THREAD

**Issue by jelabarre59** [notAperson535/OneClick-macOS-Simple-KVM#98]
The install screen for Monterey comes up far too large, and I cannot select the button to start the install.

I was able to bring up the Disk Tools and format the VM disk, but then going out to do the reinstall, I cannot see the button for starting the install, and <tab> doesn't bring me to a button that will start the install.  It toggles between the EULA scroll window and some unknown/not visible other item.  Neither of which starts the install process.  The only option is to completely quit the process with <ctrl-c> in the terminal window.

**Comment by justinclift** [comment]
@jelabarre59 ping? :smile:

**Comment by jelabarre59** [comment]
a later build worked.  Still need to re-size the wondow for my desktop though.  I think the OVMF needs to be configured for a reasonably sized VM display.
